export const CHANGE_MOBILE_TAB_ITEM = 'changeMobileTabItem'
export const SELECT_ROLE = 'selectRole'
export const GET_LOGIN_INFO = 'getLoginInfo'
export const LOGIN_INFORMATION = 'loginInformation'
export const CHANGE_WEB_ACTIVE_MENU_ITEM = 'changeWebActiveMenuItem'
export const SAVE_TOKEN = 'saveToken'

export const CHANGE_CREATING_EMPLOYEE_DIALOG = 'changeCreatingEmployeeDialog'
export const GET_EMPLOYEES_LIST = 'getEmployeesList'
export const CREATE_EMPLOYEE = 'createEmployee'
