export const CHANGE_CREATING_EMPLOYEE_DIALOG = 'employee/changeCreatingEmployeeDialog'
export const GET_EMPLOYEES_LIST = 'employee/getEmployeesList'
export const CREATE_EMPLOYEE = 'employee/createEmployee'
export const UPDATE_EMPLOYEE = 'employee/updateEmployee'
export const GET_EMPLOYEES_LIST_BY_PAGE = 'employee/getEmployeesListByPage'
export const GET_EMPLOYEES_LIST_BY_NAME = 'employee/getEmployeesListByName'
export const GET_ORDER_LIST_BY_EMPLOYEE_ID = 'employee/getOrderListByEmployeeId'

export const INIT_BUTTON_STYLE = 'employee/initButtonStyle'
export const CHANGE_BUTTON_WHEN_FREEZE = 'employee/changeButtonWhenFreeze'
export const CHANGE_BUTTON_WHEN_EDIT = 'employee/changeButtonWhenEdit'
export const CHANGE_BUTTON_WHEN_START = 'employee/changeButtonWhenStart'
export const CHANGE_BUTTON_WHEN_SAVE = 'employee/changeButtonWhenSave'
