export const CHANGE_CREATING_EMPLOYEE_DIALOG = 'employee/changeCreatingEmployeeDialog'
export const GET_EMPLOYEES_LIST = 'employee/getEmployeesList'
export const CREATE_EMPLOYEE = 'employee/createEmployee'
export const GET_EMPLOYEES_LIST_BY_PAGE = 'employee/getEmployeesListByPage'
export const GET_EMPLOYEES_LIST_BY_NAME = 'employee/getEmployeesListByName'
export const GET_ORDER_LIST_BY_EMPLOYEE_ID = 'employee/getOrderListByEmployeeId'
